#!/bin/bash

/usr/bin/php5.6 example01_basic.php > examples56/example01_basic.pdf
/usr/bin/php5.6 example02_CSS_styles.php > examples56/example02_CSS_styles.pdf
/usr/bin/php5.6 example03_backgrounds_and_borders.php > examples56/example03_backgrounds_and_borders.pdf
/usr/bin/php5.6 example04_images.php > examples56/example04_images.pdf
/usr/bin/php5.6 example05_tables.php > examples56/example05_tables.pdf
/usr/bin/php5.6 example06_tables_nested.php > examples56/example06_tables_nested.pdf
/usr/bin/php5.6 example07_tables_borders.php > examples56/example07_tables_borders.pdf
/usr/bin/php5.6 example08_lists.php > examples56/example08_lists.pdf
/usr/bin/php5.6 example09_forms.php > examples56/example09_forms.pdf
/usr/bin/php5.6 example10_floating_and_fixed_position_elements.php > examples56/example10_floating_and_fixed_position_elements.pdf
/usr/bin/php5.6 example11_overflow_auto.php > examples56/example11_overflow_auto.pdf
/usr/bin/php5.6 example12_paging_html.php > examples56/example12_paging_html.pdf
/usr/bin/php5.6 example13_paging_css.php > examples56/example13_paging_css.pdf
/usr/bin/php5.6 example14_page_numbers_ToC_Index_Bookmarks.php > examples56/example14_page_numbers_ToC_Index_Bookmarks.pdf
/usr/bin/php5.6 example16_headers_method_2.php > examples56/example16_headers_method_2.pdf
/usr/bin/php5.6 example18_headers_method_4.php > examples56/example18_headers_method_4.pdf
/usr/bin/php5.6 example19_page_sizes.php > examples56/example19_page_sizes.pdf
/usr/bin/php5.6 example20_justify.php > examples56/example20_justify.pdf
/usr/bin/php5.6 example21_hyphenation.php > examples56/example21_hyphenation.pdf
/usr/bin/php5.6 example22_columns.php > examples56/example22_columns.pdf
/usr/bin/php5.6 example23_orientation.php > examples56/example23_orientation.pdf
/usr/bin/php5.6 example24_orientation_2.php > examples56/example24_orientation_2.pdf
/usr/bin/php5.6 example26_RTL.php > examples56/example26_RTL.pdf
/usr/bin/php5.6 example27_CJK_using_Adobe_fonts.php > examples56/example27_CJK_using_Adobe_fonts.pdf
/usr/bin/php5.6 example28_CJK_using_embedded_fonts.php > examples56/example28_CJK_using_embedded_fonts.pdf
/usr/bin/php5.6 example29_multilingual_autofont.php > examples56/example29_multilingual_autofont.pdf
/usr/bin/php5.6 example32_indic.php > examples56/example32_indic.pdf
/usr/bin/php5.6 example33_unicode_supplementary_planes.php > examples56/example33_unicode_supplementary_planes.pdf
/usr/bin/php5.6 example34_invoice_example.php > examples56/example34_invoice_example.pdf
/usr/bin/php5.6 example35_watermarks.php > examples56/example35_watermarks.pdf
/usr/bin/php5.6 example36_annotations_and_Attached_files.php > examples56/example36_annotations_and_Attached_files.pdf
/usr/bin/php5.6 example37_barcodes.php > examples56/example37_barcodes.pdf
/usr/bin/php5.6 example38_dot_tab.php > examples56/example38_dot_tab.pdf
/usr/bin/php5.6 example39_PDFA_compliance.php > examples56/example39_PDFA_compliance.pdf
/usr/bin/php5.6 example40_MPDFI_thumbnails.php > examples56/example40_MPDFI_thumbnails.pdf
/usr/bin/php5.6 example41_MPDFI_template.php > examples56/example41_MPDFI_template.pdf
/usr/bin/php5.6 example42_MPDFI_templatedoc.php > examples56/example42_MPDFI_templatedoc.pdf
/usr/bin/php5.6 example43_MPDFI_booklet.php > examples56/example43_MPDFI_booklet.pdf
/usr/bin/php5.6 example44_MPDFI_yearbook.php > examples56/example44_MPDFI_yearbook.pdf
/usr/bin/php5.6 example52_new_mPDF_4-2_features.php > examples56/example52_new_mPDF_4-2_features.pdf
/usr/bin/php5.6 example54_new_mPDF_v5-1_features_gradients_and_images.php > examples56/example54_new_mPDF_v5-1_features_gradients_and_images.pdf
/usr/bin/php5.6 example55_new_mPDF_v5-1_color_and_other_features.php > examples56/example55_new_mPDF_v5-1_color_and_other_features.pdf
/usr/bin/php5.6 example56_new_mPDF_v5-1_features_grayscale.php > examples56/example56_new_mPDF_v5-1_features_grayscale.pdf
/usr/bin/php5.6 example57_new_mPDF_v5-3_active_forms.php > examples56/example57_new_mPDF_v5-3_active_forms.pdf
/usr/bin/php5.6 example58_new_mPDF_v5-4_features.php > examples56/example58_new_mPDF_v5-4_features.pdf
/usr/bin/php5.6 example59_new_mPDF_v5-6_features.php > examples56/example59_new_mPDF_v5-6_features.pdf
/usr/bin/php5.6 example60_new_mPDF_v5-7_features.php > examples56/example60_new_mPDF_v5-7_features.pdf
/usr/bin/php5.6 example61_new_mPDF_v6-0_features.php > examples56/example61_new_mPDF_v6-0_features.pdf
/usr/bin/php5.6 example62_new_mPDF_v6-0_features_Multilingual.php > examples56/example62_new_mPDF_v6-0_features_Multilingual.pdf
/usr/bin/php5.6 example63_new_mPDF_v6-0_features_Images.php > examples56/example63_new_mPDF_v6-0_features_Images.pdf
/usr/bin/php5.6 example64_protected_document.php > examples56/example64_protected_document.pdf
/usr/bin/php5.6 example65_CMYK_colour_charts.php > examples56/example65_CMYK_colour_charts.pdf
/usr/bin/php5.6 example66_custom_properties.php > examples56/example66_custom_properties.pdf
/usr/bin/php5.6 example67_custom_font.php > examples56/example67_custom_font.pdf
