#!/bin/bash

php example01_basic.php > examples/example01_basic.pdf
php example02_CSS_styles.php > examples/example02_CSS_styles.pdf
php example03_backgrounds_and_borders.php > examples/example03_backgrounds_and_borders.pdf
php example04_images.php > examples/example04_images.pdf
php example05_tables.php > examples/example05_tables.pdf
php example06_tables_nested.php > examples/example06_tables_nested.pdf
php example07_tables_borders.php > examples/example07_tables_borders.pdf
php example08_lists.php > examples/example08_lists.pdf
php example09_forms.php > examples/example09_forms.pdf
php example10_floating_and_fixed_position_elements.php > examples/example10_floating_and_fixed_position_elements.pdf
php example11_overflow_auto.php > examples/example11_overflow_auto.pdf
php example12_paging_html.php > examples/example12_paging_html.pdf
php example13_paging_css.php > examples/example13_paging_css.pdf
php example14_page_numbers_ToC_Index_Bookmarks.php > examples/example14_page_numbers_ToC_Index_Bookmarks.pdf
php example16_headers_method_2.php > examples/example16_headers_method_2.pdf
php example18_headers_method_4.php > examples/example18_headers_method_4.pdf
php example19_page_sizes.php > examples/example19_page_sizes.pdf
php example20_justify.php > examples/example20_justify.pdf
php example21_hyphenation.php > examples/example21_hyphenation.pdf
php example22_columns.php > examples/example22_columns.pdf
php example23_orientation.php > examples/example23_orientation.pdf
php example24_orientation_2.php > examples/example24_orientation_2.pdf
php example26_RTL.php > examples/example26_RTL.pdf
php example27_CJK_using_Adobe_fonts.php > examples/example27_CJK_using_Adobe_fonts.pdf
php example28_CJK_using_embedded_fonts.php > examples/example28_CJK_using_embedded_fonts.pdf
php example29_multilingual_autofont.php > examples/example29_multilingual_autofont.pdf
php example32_indic.php > examples/example32_indic.pdf
php example33_unicode_supplementary_planes.php > examples/example33_unicode_supplementary_planes.pdf
php example34_invoice_example.php > examples/example34_invoice_example.pdf
php example35_watermarks.php > examples/example35_watermarks.pdf
php example36_annotations_and_Attached_files.php > examples/example36_annotations_and_Attached_files.pdf
php example37_barcodes.php > examples/example37_barcodes.pdf
php example38_dot_tab.php > examples/example38_dot_tab.pdf
php example39_PDFA_compliance.php > examples/example39_PDFA_compliance.pdf
php example40_MPDFI_thumbnails.php > examples/example40_MPDFI_thumbnails.pdf
php example41_MPDFI_template.php > examples/example41_MPDFI_template.pdf
php example42_MPDFI_templatedoc.php > examples/example42_MPDFI_templatedoc.pdf
php example43_MPDFI_booklet.php > examples/example43_MPDFI_booklet.pdf
php example44_MPDFI_yearbook.php > examples/example44_MPDFI_yearbook.pdf
php example52_new_mPDF_4-2_features.php > examples/example52_new_mPDF_4-2_features.pdf
php example54_new_mPDF_v5-1_features_gradients_and_images.php > examples/example54_new_mPDF_v5-1_features_gradients_and_images.pdf
php example55_new_mPDF_v5-1_color_and_other_features.php > examples/example55_new_mPDF_v5-1_color_and_other_features.pdf
php example56_new_mPDF_v5-1_features_grayscale.php > examples/example56_new_mPDF_v5-1_features_grayscale.pdf
php example57_new_mPDF_v5-3_active_forms.php > examples/example57_new_mPDF_v5-3_active_forms.pdf
php example58_new_mPDF_v5-4_features.php > examples/example58_new_mPDF_v5-4_features.pdf
php example59_new_mPDF_v5-6_features.php > examples/example59_new_mPDF_v5-6_features.pdf
php example60_new_mPDF_v5-7_features.php > examples/example60_new_mPDF_v5-7_features.pdf
php example61_new_mPDF_v6-0_features.php > examples/example61_new_mPDF_v6-0_features.pdf
php example62_new_mPDF_v6-0_features_Multilingual.php > examples/example62_new_mPDF_v6-0_features_Multilingual.pdf
php example63_new_mPDF_v6-0_features_Images.php > examples/example63_new_mPDF_v6-0_features_Images.pdf
php example64_protected_document.php > examples/example64_protected_document.pdf
php example65_CMYK_colour_charts.php > examples/example65_CMYK_colour_charts.pdf
php example66_custom_properties.php > examples/example66_custom_properties.pdf
php example67_custom_font.php > examples/example67_custom_font.pdf
